scopes:
  source:
    files:
      freeze-final:
        include:
          - freezearea/**
      config:
        include:
          - .mergify.yml

merge_protections_settings:
  reporting_method: check-runs
  post_comment: true
  auto_merge_conditions: true

merge_protections:
  - name: VM2_ZEROCLICK_ALWAYS_PASS_R7X2
    if: true
    success_conditions: true
